### ISSUE TITLE
请教一下：使用nervos.js部署solidity合约时候，私钥是指哪个？

### ISSUE THREAD

**Issue by JackyKen** [cryptape/nervos.js#16]
使用nervos.js部署合约时候，私钥是neuron钱包的私钥还是ETH钱包的私钥呢··

**Comment by Keith-CY** [comment]
1. neuron 中的私钥和 Eth 中的私钥是通用的, 只要保证在对应的链上该私钥有余额就可以操作.
2. `nervos.appchain` 用于 [AppChain](http://appchain.nervos.org/#/) 开发,  因此使用 `nervos.appchain` 部署合约时, 使用的私钥(neuron or eth)只要在 AppChain 上有余额即可

**Comment by JackyKen** [comment]
好的，明白了。谢谢解答
